// Static World Cup 2026 prediction cards for opening week.
// Used as primary source for June 11-13; AI generation covers later dates.

const WC_PREDICTION_CARDS = {

  '2026-06-11': {
    date: '2026-06-11',
    matches: [
      {
        homeTeam: 'Mexico',
        awayTeam: 'South Africa',
        homeFlag: '🇲🇽',
        awayFlag: '🇿🇦',
        stage: 'Group A',
        kickoff: '2026-06-11T19:00:00Z',
        kickoffET: '3:00 PM ET',
        tvUS: 'FOX',
      },
      {
        homeTeam: 'South Korea',
        awayTeam: 'Czechia',
        homeFlag: '🇰🇷',
        awayFlag: '🇨🇿',
        stage: 'Group A',
        kickoff: '2026-06-12T02:00:00Z',
        kickoffET: '10:00 PM ET',
        tvUS: 'FS1',
      },
    ],
    daily_questions: [
      {
        id: 'dq1',
        question: 'Will there be a red card in any match on opening day?',
        options: ['Yes', 'No'],
        points: 2,
        type: 'yes_no',
      },
      {
        id: 'dq2',
        question: 'Total goals across both opening day matches?',
        options: ['0-1', '2-3', '4+'],
        points: 3,
        type: 'multi',
      },
      {
        id: 'dq3',
        question: 'Which team wins their opening match more convincingly?',
        options: ['Mexico (bigger margin)', 'South Korea (bigger margin)', 'Both close games'],
        points: 3,
        type: 'multi',
      },
    ],
    feature_match: {
      homeTeam: 'Mexico',
      awayTeam: 'South Africa',
      homeFlag: '🇲🇽',
      awayFlag: '🇿🇦',
      stage: 'Group A · Opening Match',
      kickoffET: '3:00 PM ET · FOX',
      venue: 'Estadio Azteca, Mexico City',
      reason: 'The World Cup opener — Mexico hosts at Estadio Azteca in front of 80,000 fans. Host nations have never lost a World Cup opener.',
      props: [
        {
          id: 'fm1',
          question: 'Match result?',
          options: ['Mexico win', 'Draw', 'South Africa win'],
          points: 3,
          type: 'multi',
        },
        {
          id: 'fm2',
          question: 'Will Mexico score in the first 30 minutes?',
          options: ['Yes', 'No'],
          points: 2,
          type: 'yes_no',
        },
        {
          id: 'fm3',
          question: 'Total goals in Mexico vs South Africa?',
          options: ['0-1', '2-3', '4+'],
          points: 2,
          type: 'multi',
        },
      ],
    },
    bonus: {
      id: 'bonus1',
      question: 'Mexico win AND at least one goal scored before halftime',
      points: 10,
      type: 'bonus',
      components: [
        'Mexico win the match',
        'Goal scored before 45th minute',
      ],
    },
  },

  '2026-06-12': {
    date: '2026-06-12',
    matches: [
      {
        homeTeam: 'Canada',
        awayTeam: 'Bosnia & Herzegovina',
        homeFlag: '🇨🇦',
        awayFlag: '🇧🇦',
        stage: 'Group B',
        kickoff: '2026-06-12T19:00:00Z',
        kickoffET: '3:00 PM ET',
        tvUS: 'FS1',
      },
      {
        homeTeam: 'USA',
        awayTeam: 'Paraguay',
        homeFlag: '🇺🇸',
        awayFlag: '🇵🇾',
        stage: 'Group D',
        kickoff: '2026-06-13T01:00:00Z',
        kickoffET: '9:00 PM ET',
        tvUS: 'FOX',
      },
    ],
    daily_questions: [
      {
        id: 'dq1',
        question: 'Will the USA score in the first half vs Paraguay?',
        options: ['Yes', 'No'],
        points: 2,
        type: 'yes_no',
      },
      {
        id: 'dq2',
        question: 'Total goals across both matches?',
        options: ['0-2', '3-4', '5+'],
        points: 3,
        type: 'multi',
      },
      {
        id: 'dq3',
        question: 'Will there be a red card today?',
        options: ['Yes', 'No'],
        points: 2,
        type: 'yes_no',
      },
    ],
    feature_match: {
      homeTeam: 'USA',
      awayTeam: 'Paraguay',
      homeFlag: '🇺🇸',
      awayFlag: '🇵🇾',
      stage: 'Group D · USA Debut',
      kickoffET: '9:00 PM ET · FOX',
      venue: 'SoFi Stadium, Los Angeles',
      reason: 'USA opens their home World Cup at SoFi Stadium. Biggest US soccer moment since 1994. The nation is watching.',
      props: [
        {
          id: 'fm1',
          question: 'Match result?',
          options: ['USA win', 'Draw', 'Paraguay win'],
          points: 3,
          type: 'multi',
        },
        {
          id: 'fm2',
          question: 'Will USA keep a clean sheet?',
          options: ['Yes', 'No'],
          points: 2,
          type: 'yes_no',
        },
        {
          id: 'fm3',
          question: 'Total goals in USA vs Paraguay?',
          options: ['0-1', '2-3', '4+'],
          points: 2,
          type: 'multi',
        },
      ],
    },
    bonus: {
      id: 'bonus1',
      question: 'USA win AND Paraguay do not score',
      points: 10,
      type: 'bonus',
      components: [
        'USA win the match',
        'Paraguay score 0 goals',
      ],
    },
  },

  '2026-06-13': {
    date: '2026-06-13',
    matches: [
      {
        homeTeam: 'Qatar',
        awayTeam: 'Switzerland',
        homeFlag: '🇶🇦',
        awayFlag: '🇨🇭',
        stage: 'Group B',
        kickoff: '2026-06-13T19:00:00Z',
        kickoffET: '3:00 PM ET',
        tvUS: 'FS1',
      },
      {
        homeTeam: 'Brazil',
        awayTeam: 'Morocco',
        homeFlag: '🇧🇷',
        awayFlag: '🇲🇦',
        stage: 'Group C',
        kickoff: '2026-06-13T22:00:00Z',
        kickoffET: '6:00 PM ET',
        tvUS: 'FOX',
      },
      {
        homeTeam: 'Haiti',
        awayTeam: 'Scotland',
        homeFlag: '🇭🇹',
        awayFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        stage: 'Group C',
        kickoff: '2026-06-14T01:00:00Z',
        kickoffET: '9:00 PM ET',
        tvUS: 'FS1',
      },
    ],
    daily_questions: [
      {
        id: 'dq1',
        question: 'Will Brazil score 3 or more goals vs Morocco?',
        options: ['Yes', 'No'],
        points: 2,
        type: 'yes_no',
      },
      {
        id: 'dq2',
        question: 'Total goals across all 3 matches?',
        options: ['0-3', '4-6', '7+'],
        points: 3,
        type: 'multi',
      },
      {
        id: 'dq3',
        question: 'Will there be a red card today?',
        options: ['Yes', 'No'],
        points: 2,
        type: 'yes_no',
      },
    ],
    feature_match: {
      homeTeam: 'Brazil',
      awayTeam: 'Morocco',
      homeFlag: '🇧🇷',
      awayFlag: '🇲🇦',
      stage: 'Group C',
      kickoffET: '6:00 PM ET · FOX',
      venue: 'MetLife Stadium, New Jersey',
      reason: 'Brazil opens at MetLife — the same stadium hosting the World Cup Final. Morocco knocked out favorites in 2022 and will not be intimidated.',
      props: [
        {
          id: 'fm1',
          question: 'Match result?',
          options: ['Brazil win', 'Draw', 'Morocco win'],
          points: 3,
          type: 'multi',
        },
        {
          id: 'fm2',
          question: 'Will Vinicius Jr score?',
          options: ['Yes', 'No'],
          points: 2,
          type: 'yes_no',
        },
        {
          id: 'fm3',
          question: 'Total goals in the match?',
          options: ['0-1', '2-3', '4+'],
          points: 2,
          type: 'multi',
        },
      ],
    },
    bonus: {
      id: 'bonus1',
      question: 'Brazil win AND Vinicius Jr scores',
      points: 10,
      type: 'bonus',
      components: [
        'Brazil win the match',
        'Vinicius Jr scores at least once',
      ],
    },
  },

};

module.exports = { WC_PREDICTION_CARDS };
